keycloak_openid_client_grafana_client_secret = "xxx"
keycloak_openid_client_cfa_client_secret = "xxx"
keycloak_openid_client_argocd_client_secret = "xxx"
keycloak_openid_client_gitlab_client_secret = "xxx"
keycloak_openid_client_oauth2_proxy_ondrej_client_secret = "xxx"
